po/src/main/java/id/web/knt/po/entity/Employee.java
package id.web.knt.po.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

@Entity
@Table(name="employee")
@NamedQueries({
	@NamedQuery(name="Employee.findAll",query="SELECT e FROM Employee e")
})
public class Employee implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="id")
	private Long id;
	@Column(name="first_name")
	private String firstName;
	@Column(name="last_name")
	private String lastName;
	@Embedded
	private Address address = new Address();
	
	@Override
	public String toString() {
		return "Employee [id=" + id + ", firstName=" + firstName
				+ ", lastName=" + lastName +  "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((firstName == null) ? 0 : firstName.hashCode());
		result = prime * result
				+ ((lastName == null) ? 0 : lastName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Employee other = (Employee) obj;
		if (firstName == null) {
			if (other.firstName != null)
				return false;
		} else if (!firstName.equals(other.firstName))
			return false;
		if (lastName == null) {
			if (other.lastName != null)
				return false;
		} else if (!lastName.equals(other.lastName))
			return false;
		return true;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Long getId() {
		return id;
	}
	
}

po/src/main/java/id/web/knt/po/entity/Product.java
package id.web.knt.po.entity;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

@Entity
@Table(name="product")
@NamedQueries({
	@NamedQuery(name="Product.findAll", query="SELECT p FROM Product p")
})
public class Product implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id",nullable=false)
	private Long id;
	@Column(name="name")
	private String name;
	@Column(name="price", scale=2)
	private BigDecimal price = BigDecimal.ZERO;
	
	@Override
	public String toString() {
		return "Product [id=" + id + ", name=" + name + ", price=" + price
				+ "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Product other = (Product) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public Long getId() {
		return id;
	}
}

po/src/main/java/id/web/knt/po/entity/PurchaseOrderDetail.java
package id.web.knt.po.entity;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name="purchase_order_detail")
public class PurchaseOrderDetail implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="id")
	private Long id;
	@ManyToOne
	@JoinColumn(name="product_id")
	private Product product;
	@Column(name="quantity")
	private Integer quantity = 0;
	@ManyToOne
	@JoinColumn(name="purchase_order_id")
	private PurchaseOrder purchaseOrder;
	
	@Override
	public String toString() {
		return "PurchaseOrderDetail [id=" + id + ", product=" + product
				+ ", quantity=" + quantity + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((product == null) ? 0 : product.hashCode());
		result = prime * result
				+ ((purchaseOrder == null) ? 0 : purchaseOrder.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PurchaseOrderDetail other = (PurchaseOrderDetail) obj;
		if (product == null) {
			if (other.product != null)
				return false;
		} else if (!product.equals(other.product))
			return false;
		if (purchaseOrder == null) {
			if (other.purchaseOrder != null)
				return false;
		} else if (!purchaseOrder.equals(other.purchaseOrder))
			return false;
		return true;
	}
	
	public BigDecimal getTotal() {
		return product.getPrice().multiply(new BigDecimal(quantity));
	}

	public BigDecimal getPrice() {
		return product.getPrice().multiply(new BigDecimal(quantity));
	}

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Integer getQuantity() {
		return quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public PurchaseOrder getPurchaseOrder() {
		return purchaseOrder;
	}

	public void setPurchaseOrder(PurchaseOrder purchaseOrder) {
		this.purchaseOrder = purchaseOrder;
	}

	public Long getId() {
		return id;
	}
	
}

po/src/main/java/id/web/knt/po/web/EmployeeBean.java
package id.web.knt.po.web;

import id.web.knt.po.entity.Address;
import id.web.knt.po.entity.Employee;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.Stateful;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;

import org.primefaces.context.RequestContext;
import org.primefaces.event.CloseEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


@Named("employeeBean")
@Stateful
@SessionScoped
public class EmployeeBean implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private static Logger log = LoggerFactory.getLogger("service");
	
	@PersistenceContext(type=PersistenceContextType.EXTENDED)
	private EntityManager em;
	private List<Employee> employes;
	private Employee selectedEmployee;
	private boolean dataVisible = false;
	
	@PostConstruct
	public void init(){
		findAll();
		log.info("RESET CALLED by init");
		reset();
	}
	
	public String findAll(){
		employes = em.createNamedQuery("Employee.findAll",Employee.class).getResultList();
		log.info("Employee : "+employes.size());
		dataVisible = !employes.isEmpty();
		return null;
	}
	
	private void log() {
		if (selectedEmployee.getAddress() != null)
			log.info(selectedEmployee.getAddress().toString());
		else
			log.info("address is null");
	}
	
	public void reset(){
		selectedEmployee = new Employee();
		log();
		log.info("RESET CALLED");
	}
	
//	public String create(){
//		reset();
//		return "employee";
//	}
	
	public String delete(){
		em.remove(selectedEmployee);
		log.info("RESET CALLED by delete");

		reset();
		return findAll();
	}
	
	public String persist() {
		log.info("First Name : "+selectedEmployee.getFirstName());
		log.info("Last Name : "+selectedEmployee.getLastName());
		log();
		em.merge(selectedEmployee);
		FacesContext context =  FacesContext.getCurrentInstance();
		context.addMessage(null, new FacesMessage("Saved!"));
		RequestContext request = RequestContext.getCurrentInstance();
		request.execute("employeeDialog.hide()");
		log.info("RESET CALLED by persist");

		reset();
		
		return findAll();
	}
	
	public void onClose(CloseEvent e) {
		reset();
	}

	public Employee getSelectedEmployee() {
		return selectedEmployee;
	}

	public void setSelectedEmployee(Employee selectedEmployee) {
		this.selectedEmployee = selectedEmployee;
		if (selectedEmployee != null) {
			log.info("First Name : "+selectedEmployee.getFirstName());
			log.info("Last Name : "+selectedEmployee.getLastName());
			log();
			if (selectedEmployee.getAddress() == null) {
				selectedEmployee.setAddress(new Address());
			}
		}
	}

	public boolean isDataVisible() {
		return dataVisible;
	}

	public void setDataVisible(boolean dataVisible) {
		this.dataVisible = dataVisible;
	}

	public List<Employee> getEmployes() {
		return employes;
	}


	
}

po/src/main/java/id/web/knt/po/web/ProductBean.java
package id.web.knt.po.web;

import id.web.knt.po.entity.Product;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.Stateful;
import javax.enterprise.context.SessionScoped;
import javax.enterprise.event.Event;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;

import org.primefaces.context.RequestContext;

@Named("productBean")
@Stateful
@SessionScoped
public class ProductBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@PersistenceContext(type=PersistenceContextType.EXTENDED)
	private EntityManager em;
	@Inject
	private Event<Product> productEvent;

	private List<Product> products;
	private Product selectedProduct;
	
	
	private boolean dataVisible = false;
	
	@PostConstruct
	public void init() {
		System.out.println("init called");
		reset();
	}
	
	public String findAll() {
		products = em.createNamedQuery("Product.findAll", Product.class)
				.getResultList();
		dataVisible = !products.isEmpty();
		
		return null;
	}
	
	public void reset() {
		findAll();
		selectedProduct = new Product();
		System.out.println("RESET CALLED by Product");
	}
	
	public String create() {
		reset();
		return null;
	}
	
	public String delete() {
		em.remove(selectedProduct);
		findAll();
		reset();
		
		return null;
	}
	
	public String persist() {
		productEvent.fire(em.merge(selectedProduct));
		FacesContext context =  FacesContext.getCurrentInstance();
		context.addMessage(null, new FacesMessage("Saved!"));
		RequestContext request = RequestContext.getCurrentInstance();
		request.execute("productDialog.hide()");
		
		reset();
		
		return null;
	}

	public Product getSelectedProduct() {
		return selectedProduct;
	}


	public void setSelectedProduct(Product selectedProduct) {
		this.selectedProduct = selectedProduct;
	}


	public boolean isDataVisible() {
		return dataVisible;
	}


	public void setDataVisible(boolean dataVisible) {
		this.dataVisible = dataVisible;
	}



	public List<Product> getProducts() {
		return products;
	}
	
}

po/src/main/java/id/web/knt/po/web/PurchaseOrderBean.java
package id.web.knt.po.web;

import id.web.knt.po.entity.Employee;
import id.web.knt.po.entity.Product;
import id.web.knt.po.entity.PurchaseOrder;
import id.web.knt.po.entity.PurchaseOrderDetail;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.Stateful;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.enterprise.context.SessionScoped;
import javax.enterprise.event.Observes;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;

import org.primefaces.event.CloseEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Named("purchaseOrderBean")
@Stateful
@SessionScoped
public class PurchaseOrderBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2018629357786988296L;
	private static final Logger log = LoggerFactory.getLogger(PurchaseOrderBean.class);

	@PersistenceContext(type=PersistenceContextType.TRANSACTION)
	private EntityManager em;
	
	private List<PurchaseOrder> purchaseOrders = new ArrayList<PurchaseOrder>();
	private List<Employee> users = new ArrayList<Employee>();
	private List<Product> products = new ArrayList<Product>();
	private PurchaseOrder selectedPurchaseOrder;
	private PurchaseOrderDetail selectedPurchaseOrderDetail;
	private boolean dataVisible = false;
	
	@PostConstruct
	public void init() {
		users = em.createNamedQuery("Employee.findAll",Employee.class).getResultList();
		products = em.createNamedQuery("Product.findAll", Product.class).getResultList();
		findAll();
		reset();
	}
	
	@TransactionAttribute(TransactionAttributeType.NOT_SUPPORTED)
	public String findAll() {
		purchaseOrders.clear();
		purchaseOrders.addAll(em.createNamedQuery("PurchaseOrder.findAll", PurchaseOrder.class)
				.getResultList());
		dataVisible = !purchaseOrders.isEmpty();
		return null;
	}
	
	public void reset() {
		selectedPurchaseOrder = new PurchaseOrder();
		selectedPurchaseOrderDetail = new PurchaseOrderDetail();
	}
	
	public String delete() {
		em.remove(selectedPurchaseOrder);
		
		return findAll();
	}
	
	public void onProductUpdate(@Observes Product updated) {
		boolean update = false;
		for (Product product : products) {
			if (product.equals(updated)) {
				update = true;
				product.setName(updated.getName());
				product.setPrice(updated.getPrice());
				break;
			}
		}
		if (!update) {
			products.add(updated);
		}
	}
	
	public String addPurchaseOrderDetail() {
		boolean found = false;
		for (PurchaseOrderDetail purchaseOrderDetail : selectedPurchaseOrder.getDetails()) {
			if (purchaseOrderDetail.getProduct().equals(selectedPurchaseOrderDetail.getProduct())) {
				purchaseOrderDetail.setQuantity(purchaseOrderDetail.getQuantity()+selectedPurchaseOrderDetail.getQuantity());
				found=true;
				break;
			}
		}
		if(found==false){
			selectedPurchaseOrder.addDetail(selectedPurchaseOrderDetail);
		}
		selectedPurchaseOrder.calculateTotal();
		System.out.println("Total : "+selectedPurchaseOrder.getTotal()); 
		selectedPurchaseOrderDetail = new PurchaseOrderDetail();
		return null;
	}
	
	public String persist() {
		log.info("User is not null ? " + selectedPurchaseOrder.getUser() != null ? "true" : "false");
		em.merge(selectedPurchaseOrder);
		
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Saved!"));
		
		return findAll();
	}
	
	public void onClose(CloseEvent e) {
		log.info("onClose Called");
		reset();
//		findAll();
	}
	
	public String refreshEntity(){
//		throw new CloseException();
		List<PurchaseOrderDetail> trash = new ArrayList<PurchaseOrderDetail>();
		for (PurchaseOrderDetail purchaseOrderDetail : selectedPurchaseOrder.getDetails()) {
			if (purchaseOrderDetail.getId() == null) {
				trash.add(purchaseOrderDetail);
			}
		}
		for (PurchaseOrderDetail toDelete : trash) {
			selectedPurchaseOrder.removeDetail(toDelete);
		}
		em.refresh(selectedPurchaseOrder);
		return findAll();
	}

	public PurchaseOrder getSelectedPurchaseOrder() {
		return selectedPurchaseOrder;
	}

	public void setSelectedPurchaseOrder(PurchaseOrder selectedPurchaseOrder) {
		this.selectedPurchaseOrder = em.find(PurchaseOrder.class, selectedPurchaseOrder.getId());
		selectedPurchaseOrder.calculateTotal();
		selectedPurchaseOrderDetail = new PurchaseOrderDetail();
	}

	public List<PurchaseOrder> getPurchaseOrders() {
		return purchaseOrders;
	}

	public List<Product> getProducts() {
		return products;
	}

	public boolean isDataVisible() {
		return dataVisible;
	}

	public void setDataVisible(boolean dataVisible) {
		this.dataVisible = dataVisible;
	}

	public List<Employee> getUsers() {
		return users;
	}

	public void setUsers(List<Employee> users) {
		this.users = users;
	}

	public PurchaseOrderDetail getSelectedPurchaseOrderDetail() {
		return selectedPurchaseOrderDetail;
	}

	public void setSelectedPurchaseOrderDetail(
			PurchaseOrderDetail selectedPurchaseOrderDetail) {
		this.selectedPurchaseOrderDetail = selectedPurchaseOrderDetail;
	}
	
	
}

po/src/main/webapp/pages/purchase_order.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/default.xhtml">
	<ui:define name="content">
		<h:form prependId="false" id="growlForm">
			<p:growl id="growl" showDetail="false" />
		</h:form>
		<h:form prependId="false" id="dataForm">
			<p:panel id="data" toggleable="true" toggleSpeed="250">
				<f:facet name="header">
					<h:outputText value="Purchase Orders" />
				</f:facet>
				<h:outputFormat id="noRecordsFound"
					value="#{messages.label_no_records_found}"
					rendered="#{empty purchaseOrderBean.purchaseOrders}">
					<f:param value="Purchase Order" />
				</h:outputFormat>
				<p:dataTable id="list" value="#{purchaseOrderBean.purchaseOrders}"
					var="purchaseOrder" rendered="#{!empty purchaseOrderBean.purchaseOrders}"
					resizableColumns="false" paginator="true"
					paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
					rowsPerPageTemplate="5,10,25,50" rows="10">
					<p:column headerText="Date">
						<h:outputText value="#{purchaseOrder.date}" />
					</p:column>
					<p:column headerText="Transaction Number">
						<h:outputText value="#{purchaseOrder.transactionNumber}" />
					</p:column>
					<p:column headerText="Action">
						<p:commandButton icon="ui-icon-pencil" update=":form"
							oncomplete="purchaseOrderDialog.show()">
							<f:setPropertyActionListener value="#{purchaseOrder}"
								target="#{purchaseOrderBean.selectedPurchaseOrder}" />
						</p:commandButton>
						<p:commandButton icon="ui-icon-trash" update=":form:formGrid"
							oncomplete="deleteDialog.show()">
							<f:setPropertyActionListener value="#{purchaseOrder}"
								target="#{purchaseOrderBean.selectedPurchaseOrder}" />
						</p:commandButton>
					</p:column>
				</p:dataTable>
			</p:panel>
			<p:panel>
				<p:commandLink value="#{messages.label_create}"
					onclick="purchaseOrderDialog.show()" />
				<p:commandLink value="#{messages.label_refresh}"
					action="#{purchaseOrderBean.findAll()}" 
					update=":dataForm:data :growlForm:growl :form" />
			</p:panel>
		</h:form>
		<p:dialog id="purchaseOrderEditor" widgetVar="purchaseOrderDialog"
			modal="true" header="PurchaseOrder Editor" visible="false">
			<p:ajax event="close" update=":dataForm:data :form"
				listener="#{purchaseOrderBean.onClose}" />
			<p:outputPanel id="editorPanel">
				<h:form id="form" enctype="multipart/form-data">
					<h:panelGrid columns="3" id="formGrid">
						<h:outputLabel for="transactionNumberInput"
							value="Transaction Number * :" />
						<h:inputText id="transactionNumberInput" required="true"
							value="#{purchaseOrderBean.selectedPurchaseOrder.transactionNumber}" />
						<p:message for="transactionNumberInput" display="icon" />

						<h:outputLabel for="transactionDateInput"
							value="Transaction Date * :" />
						<p:calendar id="transactionDateInput" required="true" mode="popup"
							value="#{purchaseOrderBean.selectedPurchaseOrder.date}" />
						<p:message for="transactionDateInput" display="icon" />

						<h:outputLabel for="contactInput" value="Contact * :" />
						<h:inputText id="contactInput" required="true"
							value="#{purchaseOrderBean.selectedPurchaseOrder.contact}" />
						<p:message for="contactInput" display="icon" />

						<h:outputLabel for="userInput" value="User * :" />
						<p:selectOneMenu id="userInput"
							value="#{purchaseOrderBean.selectedPurchaseOrder.user}"
							effect="fade" converter="#{employeeConverter}">
							<f:selectItem itemLabel="Select One" itemValue="" />
							<f:selectItems value="#{purchaseOrderBean.users}" var="user"
								itemLabel="#{user.firstName} #{user.lastName}"
								itemValue="#{user}" />
						</p:selectOneMenu>
						<p:message for="userInput" display="icon" />
					</h:panelGrid>
					<p:panel>
						<h:panelGrid columns="4" id="detailFormGrid">
							<h:inputText id="quantityInput" required="true" size="3"
								value="#{purchaseOrderBean.selectedPurchaseOrderDetail.quantity}" />
							<h:outputLabel for="quantityInput" value=" x " />
							<p:selectOneMenu id="productInput"
								value="#{purchaseOrderBean.selectedPurchaseOrderDetail.product}"
								effect="fade" converter="#{productConverter}">
								<f:selectItem itemLabel="Select One" itemValue="" />
								<f:selectItems value="#{purchaseOrderBean.products}"
									var="product" itemLabel="#{product.name}"
									itemValue="#{product}" />
							</p:selectOneMenu>
							<p:commandButton value="#{messages.label_add}"
								action="#{purchaseOrderBean.addPurchaseOrderDetail}"
								update="detailGrid detailFormGrid detailTotal" />
						</h:panelGrid>
					</p:panel>
					<p:panel>
						<p:dataTable id="detailGrid"
							value="#{purchaseOrderBean.selectedPurchaseOrder.details}"
							var="purchaseOrderDetail">
							<p:column headerText="Qty">
								<h:outputText value="#{purchaseOrderDetail.quantity}" />
							</p:column>
							<p:column headerText="Product">
								<h:outputText value="#{purchaseOrderDetail.product.name}" />
							</p:column>
							<p:column headerText="Price">
								<h:outputText value="#{purchaseOrderDetail.product.price}" />
							</p:column>
							<p:column headerText="Total">
								<h:outputText value="#{purchaseOrderDetail.total}" style="" />
							</p:column>
						</p:dataTable>

					</p:panel>
					<p:panel>
						<h:panelGrid columns="2" id="detailTotal">
							<h:outputLabel value="Total :" />
							<h:outputText size="5"
								value="#{purchaseOrderBean.selectedPurchaseOrder.total}" />
						</h:panelGrid>
					</p:panel>
					<p:commandButton id="btnSave" value="#{messages.label_save}"
						action="#{purchaseOrderBean.persist}"
						update="formGrid :dataForm:data :growlForm:growl"
						oncomplete="purchaseOrderDialog.hide()" />
					<p:commandButton id="btnClose" value="#{messages.label_close}"
						action="#{purchaseOrderBean.refreshEntity}"
						update="form :dataForm:data :growlForm:growl"
						oncomplete="purchaseOrderDialog.hide()" />
					<p:commandButton id="btnClose2" value="#{messages.label_close}"
						onclick="purchaseOrderDialog.hide()" type="button" />
				</h:form>
			</p:outputPanel>
		</p:dialog>
		<p:confirmDialog id="deleteEditor" widgetVar="deleteDialog"
			message="#{messages.label_delete_record}"
			header="#{messages.label_confirm_delete}">
			<p:outputPanel id="deletePanel">
				<h:form id="deleteForm">
					<p:commandButton id="deleteYesButton" value="#{messages.label_yes}"
						action="#{purchaseOrderBean.delete}"
						update=":dataForm:data :growlForm:growl"
						oncomplete="deleteDialog.hide()" />
					<p:commandButton id="deleteNoButton" value="#{messages.label_no}"
						onclick="deleteDialog.hide()" />
				</h:form>
			</p:outputPanel>
		</p:confirmDialog>
	</ui:define>
</ui:composition>